apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      name: config-server-app
      labels:
        app: config-server-app
    spec:
      containers:
        - name: config-server-app
          image: alexubuntu227/configserver
          imagePullPolicy: Always
          ports:
            - containerPort: 9296
#          env:
#            - name: EUREKA_SERVER_ADDRESS
#              valueFrom:
#                configMapKeyRef:
#                  key: eureka_service_address
#                  name: eureka-cm
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  selector:
    app: config-server-app
  ports:
    - port: 80
      targetPort: 9296